vich_uploader:
    db_driver: orm

    mappings:
        contact_images:
            uri_prefix: /images/contact
            upload_destination: '%kernel.project_dir%/public/images/contact'
            namer: Vich\UploaderBundle\Naming\SmartUniqueNamer
